name: Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Setup Ngrok
      run: |
        choco install ngrok
        ngrok authtoken ${{ secrets.NGROK_TOKEN }}

    - name: Enable RDP
      run: |
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -value 0

    - name: Start Ngrok Tunnel and Show Connection Info
      shell: powershell
      run: |
        Start-Process ngrok -ArgumentList "tcp 3389" -NoNewWindow
        Start-Sleep -Seconds 10
        try {
            $response = Invoke-WebRequest http://127.0.0.1:4040/api/tunnels -UseBasicParsing
            $json = $response.Content | ConvertFrom-Json
            $tcp = $json.tunnels[0].public_url
            Write-Output "`n🔐 RDP Address:`n$tcp"
            Write-Output "`n🖥️  Username: runneradmin"
            Write-Output "`n🔑 Password: ActionsRDP"
        } catch {
            Write-Output "❌ Failed to fetch Ngrok tunnel info. Try

